# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: managment_system_development

test:
  <<: *default
  database: managment_system_test

production:
  <<: *default
  database: managment_system_production
  username: postgres
  password: 
