descriptions:
- Collect 3 months salary slips

- Collect Experience letter

- Go through Policies

- Q & A Session

- Get Bank Account Details

- Status Report Format

- Reset Machine Password

- Strict  policy regarding salary sharing

-   Collect   Computerized  National  Identity  Card Copy of the  Employee