# config/todo_descriptions.yml
descriptions:
- Request Internet Access (DaftarKhwan)

- Request Gate Pass Access (Daftarkhwan)

- Create Email Account and add credentials in onboard document.

- Create Account at Time Station & send it to employee email address

- Invite at Slack

- Add Machine password in Onboarding Document

- Generate Contract

- Generate NDA

 Onboarding Process

- Collect 3 months salary slips

- Collect CNIC Copy

- Collect Experience letter

- Go through Policies

- Strict policy regarding salary sharing

- Q & A Session

- Get Bank Account Details

- Status Report Format

- Reset Machine Password
